config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders, only: %i[index show]
  get 'find_order', to: 'orders#find'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :status
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def index
    @message = 'Напишите свой ID и ПІБ в соответствующие поля'
  end

  def find
    @fullname = params[:fullname]
    @order = Order.find_by(id: params[:id])
    if @order && @order.fullname == @fullname

      redirect_to order_path(@order.id, @fullname)
    else
      @message = 'Ви не ввели ПІБ ' if @fullname == '' || @fullname.nil?
      @message = 'Not found' unless @order && params[:id] != ''
      @message = 'ПІБ не співпадає ' if @order && @order.fullname != @fullname && @fullname != ''
      render 'orders/index'
    end
  end

  def show
    @fullname ||= params[:fullname]
    @order = Order.find(params[:id])
    render 'orders/index' if !@order.fullname == @fullname
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppTOB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<%= form_tag find_order_path, method: :get do %>
<div class="info">
	<div class="yahho">
		<div class="col">
		    <%= text_field_tag :id , "" ,class:"form-control", placeholder:"ID"%>
		</div>
		<div class="col">
			<%= text_field_tag :fullname, "" ,class:"form-control", placeholder:"ПІБ" %>
		</div>
		<div class="col">
			<%= submit_tag 'Переглянути' ,class:"btn btn-success" %>
		</div>
	</div>
<% end %>
<div class="text"><%=@message%></div>
</div>

app/views/orders/show.html.erb
<style>
td{
	color: white;
}
</style>
<div class="info">
	<table class="table" border="3" text-align: "center" cols="4" bordercolor="green">
		<tr>
			<td>Клиент</td>
			<td>Уникальный код</td>
			<td>Причина обращения к нам</td>
			<td>Статус</td>
		</tr>
		<tr>
			<td><%=@order.fullname%></td>
			<td><%=@order.id%></td>
			<td><%=@order.why%></td>
			<td><%=@order.status.name%></td>
		</tr>
	</table>
</div>

app/views/pages/index.html.erb
<header>
	<div class="info">
		<h2 class="title">Приветствуем тебя, юнный искатель, мы поможем тебе отследить твою заявку в нашем магазине</h2>
		<h5 class="subtitle">Чтобы найти вашу заявку, предлагаем вам перейти на эту страницу:</h5>
		<div class="search">
			<h3 class="subtitle"><%= link_to "Отследить заявку", orders_path %></h3>
		</div>
	</div>
</header>